### ISSUE TITLE
Cura crashes due to conversion exception 

### ISSUE THREAD

**Issue by jellespijker** [YiamiYo/Cura-PowerCostPlugin#1]
I noticed some logs showing hard crashes of Cura running your plugin, due to an uncaught exception when converting string to float. See the shared Sentry report. https://ultimaker-o7.sentry.io/share/issue/96a2f1f7dadc40f5be049849b82e1703/

The crashes occur in this line: https://github.com/YiamiYo/Cura-PowerCostPlugin/blob/742f5539ed058b6ed4ba981f01437b541e813dd0/PowerCostExtension.py#L59
They probably happens due to the user locale and the usage of a `,` instead of a `.` in the string. Should be easy enough to fix. You might also want to add a `try...except` block when performing a conversion.

**Comment by jellespijker** [comment]
Created a quick fix for this, didn't test the code

**Comment by YiamiYo** [comment]
Fixed in 0.1.2
