### ISSUE TITLE
Does not show full cost

### ISSUE THREAD

**Issue by pauluchin** [YiamiYo/Cura-PowerCostPlugin#3]
Hello, I am currently using version 0.1.2 and it does not show the fully calculated cost, I use Cura 5.4.0.

![Captura](https://github.com/YiamiYo/Cura-PowerCostPlugin/assets/561695/8932580f-0242-4c3f-9335-a626bd140825)

Thank you very much for your time and work

**Comment by YiamiYo** [comment]
Hiho! Yeah, that's my bad. I assumed a few digits would be enough for power cost, but I didn't take into account countries with low value currencies. I'll increase the width and publish a new version. Thanks!

**Comment by pauluchin** [comment]
Thanks for the correction, I already installed it and it works great
