### ISSUE TITLE
Cost is Blank

### ISSUE THREAD

**Issue by Belliqueu** [YiamiYo/Cura-PowerCostPlugin#4]
Nothing is showing up for the cost. What did I do wrong?

![image](https://github.com/YiamiYo/Cura-PowerCostPlugin/assets/88670754/3325a54c-5ef2-4fe6-8221-1c3b81beff58)

**Comment by YiamiYo** [comment]
Is this still a problem with the latest version? (v0.1.3)

**Comment by Belliqueu** [comment]
Confirmed fixed! Thank you! <3
    On Sunday, August 13, 2023 at 03:36:51 AM EDT, George Mathioudakis ***@***.***> wrote:  
 
 


Is this still a problem with the latest version? (v0.1.3)
