### ISSUE TITLE
Causing crash

### ISSUE THREAD

**Issue by ThomAce** [YiamiYo/Cura-PowerCostPlugin#5]
Conversion in different language settings might fail and resulting complete crash in Creality Slicer.

Traceback (most recent call last):
  File "C:\Users\<...>PowerCostExtension.py", line 59, in currentPrintTimeChanged
    powerCostPerKWh = float(config.get("power_cost_per_kwh", "0.0").strip())
ValueError: could not convert string to float: '0,08'

As input, the slicer does not accept dot (".") for numbers like 1.0. Instead it accepts 1,0

As interim and dumb solution, I changed the code to:

powerCostPerKWh = float(config.get("power_cost_per_kwh", "0.0").replace(",", ".").strip())

**Comment by YiamiYo** [comment]
This is already fixed in v0.1.2+ with 83e9c2e44370c1e6b4001221f88d0538248719fc

**Comment by ThomAce** [comment]
Thanks. Unfortunately, in Creality Slicer, only 0.1.1 was available. I'll update the files manually. When I open the marketplace, I can see the 0.1.2, however it is not updating to current version.
